"""
delta/report.py
Renders a DeltaItem list into:
  1. A human-readable Markdown report
  2. A machine-parseable JSON report
Both are written to ./reports/ and the paths returned.
"""
from __future__ import annotations
import json
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path

from src.delta.engine import DeltaItem
from src.canonical.model import CanonicalDocument

REPORTS_DIR = Path(__file__).parent.parent.parent / "reports"
REPORTS_DIR.mkdir(exist_ok=True)


def render(
    items: list[DeltaItem],
    doc_a: CanonicalDocument,
    doc_b: CanonicalDocument,
    run_id: str = "",
) -> tuple[Path, Path]:
    """Write MD + JSON reports. Returns (md_path, json_path)."""
    now     = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    stem    = f"delta_{run_id}_{now}" if run_id else f"delta_{now}"
    md_path   = REPORTS_DIR / f"{stem}.md"
    json_path = REPORTS_DIR / f"{stem}.json"

    md_path.write_text(  _to_markdown(items, doc_a, doc_b), encoding="utf-8")
    json_path.write_text(_to_json(items, doc_a, doc_b, now), encoding="utf-8")

    return md_path, json_path


def _to_markdown(
    items: list[DeltaItem],
    doc_a: CanonicalDocument,
    doc_b: CanonicalDocument,
) -> str:
    added    = [i for i in items if i.change_type == "added"]
    removed  = [i for i in items if i.change_type == "removed"]
    modified = [i for i in items if i.change_type == "modified"]

    lines = [
        f"# Delta Report",
        f"",
        f"| Field | Value |",
        f"|---|---|",
        f"| Document A (base)     | `{doc_a.pid}` (rev: {doc_a.revision or 'N/A'}) |",
        f"| Document B (revised)  | `{doc_b.pid}` (rev: {doc_b.revision or 'N/A'}) |",
        f"| Format A | {doc_a.format} |",
        f"| Format B | {doc_b.format} |",
        f"| Total changes | {len(items)} |",
        f"| Added | {len(added)} |",
        f"| Removed | {len(removed)} |",
        f"| Modified | {len(modified)} |",
        f"",
        f"---",
        f"",
    ]

    def _section(title: str, emoji: str, group: list[DeltaItem]) -> list[str]:
        if not group:
            return [f"## {emoji} {title}", "", "_No changes in this category._", ""]
        sec = [f"## {emoji} {title} ({len(group)})", ""]
        for item in group:
            page_label = f"p.{item.page_b or item.page_a}"
            sec.append(f"### `{item.change_id}` · {item.content_type} · {page_label}")
            sec.append(f"**Confidence:** {item.confidence:.0%}")
            if item.old_value:
                sec.append(f"- **Before:** {item.old_value[:200]}")
            if item.new_value:
                sec.append(f"- **After:**  {item.new_value[:200]}")
            sec.append(f"> {item.description}")
            sec.append("")
        return sec

    lines += _section("Added",    "✅", added)
    lines += _section("Removed",  "❌", removed)
    lines += _section("Modified", "✏️", modified)

    lines += [
        "---",
        "",
        "_This report is machine-generated by delta-chat. "
        "Review each item against the source documents before acting on it._",
    ]

    return "\n".join(lines)


def _to_json(
    items: list[DeltaItem],
    doc_a: CanonicalDocument,
    doc_b: CanonicalDocument,
    timestamp: str,
) -> str:
    payload = {
        "timestamp": timestamp,
        "doc_a": {"pid": doc_a.pid, "format": doc_a.format, "revision": doc_a.revision},
        "doc_b": {"pid": doc_b.pid, "format": doc_b.format, "revision": doc_b.revision},
        "summary": {
            "total":    len(items),
            "added":    sum(1 for i in items if i.change_type == "added"),
            "removed":  sum(1 for i in items if i.change_type == "removed"),
            "modified": sum(1 for i in items if i.change_type == "modified"),
        },
        "changes": [_item_to_dict(i) for i in items],
    }
    return json.dumps(payload, indent=2)


def _item_to_dict(item: DeltaItem) -> dict:
    return {
        "change_id":    item.change_id,
        "change_type":  item.change_type,
        "content_type": item.content_type,
        "page_a":       item.page_a,
        "page_b":       item.page_b,
        "old_value":    item.old_value,
        "new_value":    item.new_value,
        "description":  item.description,
        "confidence":   item.confidence,
        "bbox_a":       list(item.bbox_a) if item.bbox_a else None,
        "bbox_b":       list(item.bbox_b) if item.bbox_b else None,
    }
